### ISSUE TITLE
Update SharemindCHeaders to version 1.3.0

### ISSUE THREAD

**Issue by Mikerah** [sharemind-sdk/cheaders#1]
In an attempt to build the sharemind SDK, it turns out that the cmake file for CXXHeaders ([here](https://github.com/sharemind-sdk/cxxheaders/blob/master/CMakeLists.txt)) requires version 1.3.0 of cheaders but the one available in this repo is only for version 1.2.0.

**Comment by druid** [comment]
Thank you for reporting this. Indeed, we had somehow missed this repo when publishing updates for the 2020.12 release. I pushed the stable-1.3 branch to Github now and also forwarded master accordingly. It should work now.
